openapi: 3.0.1
info:
  version: 1.0.0
  title: JSONPlaceholder API
  description: JSONPlaceholder API from https://jsonplaceholder.typicode.com
paths:
  /albums:
    get:
      operationId: albums
      summary: Get the list of albums
      responses:
        '200':
          description: Received the list of albums successfully
