openapi: 3.0.1
info:
  version: 1.0.0
  title: JSONPlaceholder API
  description: JSONPlaceholder API from https://jsonplaceholder.typicode.com
paths:
  /comments:
    get:
      operationId: comments
      summary: Get the list of comments
      responses:
        '200':
          description: Received the list of comments successfully
